import { ReactNode } from 'react'
import PlayersProvider from '../context/PlayersContext'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Tic-Tac-Toe',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: ReactNode}) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <PlayersProvider>
          {children}
        </PlayersProvider>
      </body>
    </html>
  )
}
